window.ClientGame={dimensiones_casilla:[576,288],Sala:{miAvatar:null,container:DGame,NameSesion:"",comprobarSesion(NameSesion){return this.NameSesion==NameSesion},src_image_baldosa_principal:'',images:{},estructura:{casillas:[],nCasillas_x:0,nCasillas_y:0,image_suelo:null},info:{},cuerpos:{avatares:{},furnis:{},other:{}},verAvatar(id){return this.cuerpos.avatares[id]||null},agregarCuerpo(tipoCuerpo,dataCuerpo){var cuerpo=new Avatar(dataCuerpo.id,dataCuerpo.coords,dataCuerpo.info);var dondeGuardar=({avatar:'avatares',furni:'furnis'})[tipoCuerpo]||'other';this.cuerpos[dondeGuardar][cuerpo.id]=cuerpo;return cuerpo},verCasilla(x,y){return this.estructura.casillas[x]?(this.estructura.casillas[x][y]||null):null},Controles:{selector:{casilla:null,coordenadas:null}}},zoom:.5,cambiarZoom(tipo,multiplo=.1){var zoom=ClientGame.zoom;zoom+=multiplo*(tipo=="disminuir"?-1:1);if(zoom<.1){zoom=.1}else if(zoom>1){zoom=1}
ClientGame.zoom=zoom},Game:{camara:[0,0],pos_mouse_camara:[],timeIniciado:0,verTiempo(){return(new Date).getTime()-this.timeIniciado},moverCamara(x,y){this.camara[0]=x;this.camara[1]=y}},Canvas:{id_canvas:[],elementos:{},ctx:{},buffer_elementos:{},buffer_ctx:{},agregarCanvas(canvas){var name_canvas=canvas.getAttribute('data-game');this.elementos[name_canvas]=canvas;this.ctx[name_canvas]=canvas.getContext('2d');this.buffer_elementos[name_canvas]=document.createElement('canvas');this.buffer_ctx[name_canvas]=this.buffer_elementos[name_canvas].getContext('2d');this.id_canvas.push(name_canvas);this.ajustarDimension(name_canvas)},ajustarDimension(name_canvas){this.elementos[name_canvas].width=innerWidth;this.elementos[name_canvas].height=innerHeight;this.buffer_elementos[name_canvas].width=innerWidth;this.buffer_elementos[name_canvas].height=innerHeight},reajustarDimensionesCanvas(){var canvas=this.id_canvas;for(var i in canvas){this.ajustarDimension(canvas[i])}},insertarImagen(name_canvas,image,pos_x,pos_y,fwidth,fheight,image_width,image_height,opacidad,cutImage_x=0,cutImage_y=0){if(!fwidth)fwidth=image.width;if(!fheight)fheight=image.height;if(!image_width)image_width=fwidth;if(!image_height)image_height=fheight;var ctx=this.verCtxBuffer(name_canvas);if(!ctx)return null;ctx.drawImage(image,cutImage_x,cutImage_y,fwidth,fheight,pos_x,pos_y,image_width,image_height)},verCanvasBuffer(name_canvas){return this.buffer_elementos[name_canvas]},verCanvas(name_canvas){return this.elementos[name_canvas]},verCtxBuffer(name_canvas){return this.buffer_ctx[name_canvas]},verCtx(name_canvas){return this.ctx[name_canvas]},terminarBuffer(name_canvas){var canvasBuffer=this.verCanvasBuffer(name_canvas),canvas=this.verCanvas(name_canvas),ctxBuffer=this.verCtxBuffer(name_canvas),ctx=this.verCtx(name_canvas);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(canvasBuffer,0,0);ctxBuffer.clearRect(0,0,canvasBuffer.width,canvasBuffer.height)}},Images:{imagesCargadas:{images_preparadas:{},images_cargando:{}},cargar($images,$tipo){var tiposAdmitidos=['array','asociativo'];if(!tiposAdmitidos.includes($tipo))
$tipo=tiposAdmitidos[0];return new Promise(function(success,fail){var images_mandar,nImagenes_no_cargadas=0;if($tipo=='array'){images_mandar=[]}else if($tipo=='asociativo'){images_mandar={}}
var images=$images.slice(),nImagesProcesadas=0,procesarImagen=function(){if(!images.length){exito();return}
var imagenCargada=function(image,index){if(image!==undefined&&index!==undefined){images_mandar[index]=image}
nImagesProcesadas++;images.splice(0,1);procesarImagen()}
var verImg=images[0];var src=Array.isArray(verImg)?verImg[1]:verImg[0],index=Array.isArray(verImg)?verImg[0]:nImagesProcesadas;var imagenYa_Cargada=ClientGame.Images.imagesCargadas.images_preparadas[src];if(imagenYa_Cargada){return imagenCargada(imagenYa_Cargada,index)}
var imagenYaEnPreparacion=ClientGame.Images.imagesCargadas.images_cargando[src];if(imagenYaEnPreparacion){let EventoImagenCargar=function(src_cargado,img_cargado){if(src==src_cargado){ClientGame.eliminarEvento('ImageCargada',EventoImagenCargar);imagenCargada(img_cargado,index)}};ClientGame.agregarEvento('ImageCargada',EventoImagenCargar);return}
var img=new Image();img.src=src;ClientGame.Images.imagesCargadas.images_cargando[src]=img;img.onload=function(){ClientGame.procesarEvento('ImageCargada',[src,img]);ClientGame.Images.imagesCargadas.images_cargando[src]=null;ClientGame.Images.imagesCargadas.images_preparadas[src]=this;imagenCargada(img,index)}
img.onerror=function(){ClientGame.procesarEvento('ImageCargaErrada',[src,img]);nImagenes_no_cargadas++;imagenCargada()}},exito=function(){success({images:images_mandar,no_cargadas:nImagenes_no_cargadas})};procesarImagen()})}},eventos:{},eventos_configs:{},agregarEvento($name,$func,$bUnaVez){if(!this.eventos[$name])
this.eventos[$name]=[];if(!this.eventos_configs[$name])
this.eventos_configs[$name]=[];this.eventos[$name].push($func);this.eventos_configs[$name].push({unavez:$bUnaVez?1:0})},eliminarEvento($name,$func){if(this.eventos[$name]){var indx=this.eventos[$name].indexOf($func);if(indx!=-1){this.eventos[$name].splice(indx,1);this.eventos_configs[$name].splice(indx,1)}}},procesarEvento($name,parms=[]){var eventos=this.eventos[$name],configs=this.eventos_configs[$name];if(!Array.isArray(parms))
parms=[];if(eventos){eventos=eventos.slice();configs=configs.slice();for(var i in eventos){let func=eventos[i],conf=configs[i];try{if(func){func(...parms);if(conf.unavez)this.eliminarEvento($name,func)}}catch(err){throw err}}}}}
{let canvas=ClientGame.Sala.container.querySelectorAll('canvas[data-game]');for(var i=0;i<canvas.length;i++){let c=canvas[i];ClientGame.Canvas.agregarCanvas(c)}
window.addEventListener('resize',function(){ClientGame.Canvas.reajustarDimensionesCanvas()})}
{let Sala=ClientGame.Sala,Canvas=ClientGame.Canvas,Game=ClientGame.Game;Sala.procesarSala=function(NameSesion="",images={},estructura={}){Sala.NameSesion=NameSesion;Sala.info.nombre='';Sala.estructura.nCasillas_x=estructura.nCasillas_x;Sala.estructura.nCasillas_y=estructura.nCasillas_y;Sala.crearCasillas(estructura.nCasillas_x,estructura.nCasillas_y);Sala.Controles.preparar();var imagesCargar=[];imagesCargar.push(['baldosa_principal',images.baldosa_principal||'images/salas/AL8BALDOSA@8x-min_v2.png?1']);imagesCargar.push(['selector','images/salas/SELECTORA_TEST.png']);return new Promise(function(success,fail){ClientGame.Images.cargar(imagesCargar,"asociativo").then(function(imgEntregadas){if(!Sala.comprobarSesion(NameSesion))return"Está en otra sala.";Sala.images=imgEntregadas.images;Sala.construirSuelo().then(function(ImageSuelo){if(!Sala.comprobarSesion(NameSesion))return"Está en otra sala.";Sala.estructura.image_suelo=ImageSuelo;Game.timeIniciado=(new Date).getTime();Game.reproducir();success()})}).catch(function(err){alert("No se pudo cargar las imágenes. "+err);fail(err)})})}
Sala.crearCasillas=function(nCasillas_x,nCasillas_y){for(var x=0;x<nCasillas_x;x++){for(var y=0;y<nCasillas_y;y++){if(!Sala.estructura.casillas[x])
Sala.estructura.casillas[x]=[];Sala.estructura.casillas[x][y]=new SalaCasilla(x,y)}}}
Sala.construirSuelo=function(){var canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=ClientGame.dimensiones_casilla[0]+(ClientGame.Sala.estructura.nCasillas_y-1)*(ClientGame.dimensiones_casilla[0]/2+1)+(ClientGame.Sala.estructura.nCasillas_x-1)*(ClientGame.dimensiones_casilla[0]/2+1);canvas.height=(ClientGame.Sala.estructura.nCasillas_y+1)*(ClientGame.dimensiones_casilla[1]/2)+(ClientGame.Sala.estructura.nCasillas_x-1)*(ClientGame.dimensiones_casilla[1]/2);var casillas=Sala.estructura.casillas;for(var x in casillas){for(var y in casillas[x]){let ca=casillas[x][y];ctx.drawImage(Sala.images.baldosa_principal,ca.posicion.px,ca.posicion.py)}}
return new Promise(function(success,fail){var imageSuelo=new Image();canvas.toBlob(function(blob){imageSuelo.src=URL.createObjectURL(blob);imageSuelo.onload=function(){success(imageSuelo)}})})}
class SalaCasilla{coord_x=0;coord_y=0;posicion={px:0,py:0}
constructor(coord_x,coord_y){this.coord_x=coord_x;this.coord_y=coord_y;this.posicion.px=((Sala.estructura.nCasillas_x-1)*(ClientGame.dimensiones_casilla[0]/2+1))+coord_y*(ClientGame.dimensiones_casilla[0]/2+1)-coord_x*(ClientGame.dimensiones_casilla[0]/2+1)
this.posicion.py=coord_y*(ClientGame.dimensiones_casilla[1]/2)+coord_x*(ClientGame.dimensiones_casilla[1]/2)}}}
{var Sala=ClientGame.Sala,Game=ClientGame.Game;Sala.Controles.calcularCasilla=function(x,y){var casilla_seleccionada=null,tamano_casilla=ClientGame.dimensiones_casilla.slice();tamano_casilla[0]*=ClientGame.zoom;tamano_casilla[1]*=ClientGame.zoom;var cursor_coords=[x-((Sala.estructura.nCasillas_x-1)*(tamano_casilla[0]/2+1))-(tamano_casilla[0]*.34),y],coords_x=Math.floor(cursor_coords[0]/(tamano_casilla[0]/2+1)),coords_y=Math.floor((cursor_coords[1]-(coords_x*tamano_casilla[1]/2))/tamano_casilla[1]);coords_x=Math.floor((cursor_coords[0]+(coords_y*(tamano_casilla[0]/2+1)))/(tamano_casilla[0]/2+1));return[coords_y,coords_x]}
var moverSala={tipoClick:null,clicked:!1,clicked_x:0,clicked_y:0,camara:Game.camara.slice()}
Sala.Controles.EVENTO_mousedown=function(event){var x=event.clientX,y=event.clientY;if(event.touches&&event.touches[0]){x=event.touches[0].clientX;y=event.touches[0].clientY}
moverSala.tipoClick=event.type;moverSala.clicked=!0;moverSala.clicked_x=x-Game.camara[0];moverSala.clicked_y=y-Game.camara[1];moverSala.camara=Game.camara.slice()}
Sala.Controles.EVENTO_mousemove=function(event){var x=event.clientX,y=event.clientY;if(event.touches&&event.touches[0]){x=event.touches[0].clientX;y=event.touches[0].clientY}
if(moverSala.clicked){Game.moverCamara(x-moverSala.clicked_x,y-moverSala.clicked_y)}
var coordenadas=Sala.Controles.calcularCasilla(x-Game.camara[0],y-Game.camara[1]);Sala.Controles.selector.coordenadas=coordenadas.slice();Sala.Controles.selector.casilla=Sala.verCasilla(coordenadas[0],coordenadas[1]);Game.pos_mouse_camara[0]=x-Game.camara[0];Game.pos_mouse_camara[1]=y-Game.camara[1]}
Sala.Controles.EVENTO_mouseup=function(x,y){moverSala.clicked=!1;if(Game.camara.toString()==moverSala.camara.toString()){if(Sala.Controles.selector.casilla){let coords=Sala.Controles.selector.coordenadas;CAMINAR_YO(Sala.miAvatar,coords[0],coords[1])}}}
{let ultimoWheel=0;Sala.container.addEventListener('wheel',function(event){var timestamp=(new Date).getTime();if(timestamp-ultimoWheel<200)return;ultimoWheel=timestamp;ClientGame.cambiarZoom(event.deltaY<0?'aumentar':'disminuir')})}
Sala.Controles.preparar=function(){Sala.container.addEventListener('mousedown',Sala.Controles.EVENTO_mousedown);Sala.container.addEventListener('mousemove',Sala.Controles.EVENTO_mousemove);Sala.container.addEventListener('mouseup',Sala.Controles.EVENTO_mouseup);Sala.container.addEventListener('touchstart',Sala.Controles.EVENTO_mousedown);Sala.container.addEventListener('touchmove',Sala.Controles.EVENTO_mousemove);Sala.container.addEventListener('touchend',Sala.Controles.EVENTO_mouseup)}
Sala.Controles.cancelar=function(){Sala.container.removeEventListener('mousedown',Sala.Controles.EVENTO_mousedown);Sala.container.removeEventListener('mousemove',Sala.Controles.EVENTO_mousemove);Sala.container.removeEventListener('mouseup',Sala.Controles.EVENTO_mousedown);Sala.container.removeEventListener('touchstart',Sala.Controles.EVENTO_mousedown);Sala.container.removeEventListener('touchmove',Sala.Controles.EVENTO_mousemove);Sala.container.removeEventListener('touchend',Sala.Controles.EVENTO_mouseup)}}
{let Game=ClientGame.Game,Canvas=ClientGame.Canvas,Sala=ClientGame.Sala;Game.reproducir=function(){window.requestAnimationFrame(Game.reproducir);var selector=Sala.Controles.selector;var time=Game.verTiempo();Game.dibujarSuelo();var bot_caminador=Sala.verAvatar('bot_caminador');if(!window.botCaminador_ultimaComprobacion)
window.botCaminador_ultimaComprobacion=time;if(bot_caminador&&!bot_caminador.caminata.enCurso&&time-window.botCaminador_ultimaComprobacion>=2000&&bot_caminador.preparado){CAMINAR_YO(bot_caminador,Math.floor(Sala.estructura.nCasillas_x*Math.random()),Math.floor(Sala.estructura.nCasillas_y*Math.random()));window.botCaminador_ultimaComprobacion=time}
if(selector.casilla){Canvas.insertarImagen('principal',Sala.images.selector,Game.camara[0]+(selector.casilla.posicion.px*ClientGame.zoom),Game.camara[1]+(selector.casilla.posicion.py*ClientGame.zoom),0,0,Sala.images.selector.width*ClientGame.zoom,Sala.images.selector.height*ClientGame.zoom)}
var avataresCaminando=Avatar.AvataresCaminando.slice();for(var i in avataresCaminando){avataresCaminando[i].calcularCaminata(time)}
var capas=CapaGame.Capas;for(var i in capas){capas[i].visualizarTodo()}
Canvas.terminarBuffer('principal')}
Game.dibujarSuelo=function(){Canvas.insertarImagen('principal',Sala.estructura.image_suelo,Game.camara[0],Game.camara[1],0,0,Sala.estructura.image_suelo.width*ClientGame.zoom,Sala.estructura.image_suelo.height*ClientGame.zoom)}
Game.moverCamara=function(x,y){x=Math.floor(x);y=Math.floor(y);Game.camara=[x,y]}}
class CapaGame{static Capas=[];static CapasPorId={};id="";x=0;y=0;zIndex=0;cuerposAlojados=[];constructor(x,y){this.x=x;this.y=y;this.zIndex=(x*ClientGame.Sala.estructura.nCasillas_y)+y;this.id=x+'-'+y}
visualizarTodo(){var time=ClientGame.Game.verTiempo();for(var i in this.cuerposAlojados){this.cuerposAlojados[i].visualizar(time)}}
agregarCuerpo(cuerpo){this.cuerposAlojados.push(cuerpo)}
retirarCuerpo(cuerpo){var indx=this.cuerposAlojados.indexOf(cuerpo);if(indx!=-1){this.cuerposAlojados.splice(indx,1)}
if(!this.cuerposAlojados.length){this.borrarCapa()}}
borrarCapa(){CapaGame.CapasPorId[this.id]=null;var indx=CapaGame.Capas.indexOf(this);if(!indx)
CapaGame.Capas.splice(indx,1)}
static verCapa(capaId){return CapaGame.CapasPorId[capaId]||null}
static crearCapa(x,y){var capa_existente=CapaGame.verCapa(x,y);if(capa_existente){return capa_existente}else{var crearCapa=new CapaGame(x,y);CapaGame.CapasPorId[x+'-'+y]=crearCapa;CapaGame.Capas.push(crearCapa);CapaGame.OrdenarCapas();return crearCapa}}
static OrdenarCapas(){CapaGame.Capas.sort(function(a,b){return a.zIndex-b.zIndex})}}
class CuerpoSala{id="";tipo="";preparado=!1;info={nombre:'',sexo:0}
coords={cx:0,cy:0,px:0,py:0,caminata_x:0,caminata_y:0}
image={width:0,height:0,images:[],fotogramaX:[0],fotogramaY:[0]}
animaciones=[];CapaId=null;constructor(tipo,id,coords,info){this.tipo=tipo;this.id=id;this.coords.cx=coords.cx;this.coords.cy=coords.cy}
preparar(){this.preparado=!0}
get MiCapa(){return CapaGame.verCapa(this.CapaId)}
get MiCasilla(){return ClientGame.Sala.verCasilla(this.coords.cx,this.coords.cy)}
ajustarEnCapas(){this.borrarDeCapa();var crearCapa=CapaGame.crearCapa(this.coords.cx,this.coords.cy);crearCapa.agregarCuerpo(this);this.CapaId=crearCapa.id}
borrarDeCapa(){var miCapa=this.MiCapa;if(!miCapa)return;miCapa.retirarCuerpo(this)}
visualizar(time){var Canvas=ClientGame.Canvas,cuerpo=this,posicion=cuerpo.posicion,images=this.images,camara_game=ClientGame.Game.camara;this.procesarAnimaciones(time);for(var i in images){let img=images[i],ftgrama_x=(cuerpo.image.fotogramaX[i]||cuerpo.image.fotogramaX[0]||0)*cuerpo.image.width,ftgrama_y=(cuerpo.image.fotogramaY[i]||cuerpo.image.fotogramaY[0]||0)*cuerpo.image.height;Canvas.insertarImagen('principal',img,camara_game[0]+posicion.x,camara_game[1]+posicion.y,cuerpo.image.width,cuerpo.image.height,cuerpo.image.width*ClientGame.zoom,cuerpo.image.height*ClientGame.zoom,0,ftgrama_x,ftgrama_y)}}
get posicion(){var x=0,y=0;var verCasilla=ClientGame.Sala.verCasilla(this.coords.cx,this.coords.cy);x+=verCasilla.posicion.px+this.coords.px+this.coords.caminata_x;y+=verCasilla.posicion.py+this.coords.py+this.coords.caminata_y;return{x:x*ClientGame.zoom,y:y*ClientGame.zoom}}
get images(){return this.image.images}
crearAnimacion(capa=0,name="",tipo="perpetua",fotogramas=[],time_por_fotograma=100){if(!Array.isArray(fotogramas)||!fotogramas.length)
return;if(isNaN(time_por_fotograma))
time_por_fotograma=300;this.animaciones[capa]={name:name,tipo:tipo,capa:capa,fotogramas:fotogramas,time_inicio:ClientGame.Game.verTiempo(),time_por_fotograma:Number(time_por_fotograma),fotogramaActual:this.image.fotogramaX[capa]}}
cancelarAnimacion(capa){var animacion=this.animaciones[capa];if(animacion){if(animacion.fotogramaActual!==undefined){this.image.fotogramaX[animacion.capa]=animacion.fotogramaActual}}
this.animaciones[capa]=null}
procesarAnimaciones(time){for(var i in this.animaciones){let animacion=this.animaciones[i];if(!animacion)continue;let duracionTotal=(animacion.time_por_fotograma*animacion.fotogramas.length),time_progreso=((time-animacion.time_inicio)%(duracionTotal+1))/duracionTotal;this.image.fotogramaX[animacion.capa]=animacion.fotogramas[Math.floor((animacion.fotogramas.length)*time_progreso)]}}
enfocarCamara(){var miPosicion=this.posicion,canvasPrincipal=ClientGame.Canvas.verCanvas('principal'),miCasilla=this.MiCasilla;var new_x=((miCasilla.posicion.px*-1)*ClientGame.zoom)+((canvasPrincipal.width-(ClientGame.dimensiones_casilla[0]*ClientGame.zoom))/2),new_y=((miPosicion.y*-1)*ClientGame.zoom)+((canvasPrincipal.height-(this.image.height*ClientGame.zoom))/2);Game.moverCamara(new_x,new_y)}}
const SRC_AVATAR_IMAGES_BASE='images/avatares/';class Avatar extends CuerpoSala{static AvataresCaminando=[];imagesEstados={parado:{cabeza:[],cuerpo:[]},}
estadoActual="parado";apariencia={cabeza:1,sexo:0}
caminata={enCurso:!1,casillas_recorrer:[],time_inicio:0,time_inicio_casilla:0,time_por_casilla:500,caminos_recorridos:0}
constructor(id,coords,info){super('avatar',id,coords,info);this.apariencia.sexo=this.info.sexo;this.ubicarCuerpo();var avatar=this;this.cargarImagenes().then(function(){avatar.establecerApariencia();avatar.preparar()})}
get GET_SRC_IMAGES_AVATAR(){return SRC_AVATAR_IMAGES_BASE+(this.apariencia.sexo?'fem':'mas')+'/'}
ubicarCuerpo(){this.ajustarEnCapas()}
cargarImagenes(){var images_cargar=[];for(var estado in this.imagesEstados){images_cargar.push(['cabeza_'+estado+'_c',this.GET_SRC_IMAGES_AVATAR+'cabezas/'+this.apariencia.cabeza+'/'+estado+'.png']);images_cargar.push(['cuerpo_'+estado+'_c',this.GET_SRC_IMAGES_AVATAR+estado+'.png'])}
var avatar=this;return new Promise(function(success,fail){ClientGame.Images.cargar(images_cargar).then(function(imagesResult){var images_cargadas=imagesResult.images;for(var name_image in images_cargadas){let name_div=name_image.split('_'),donde_guardar=name_div[0],name_estado=name_div[1];avatar.imagesEstados[name_estado][donde_guardar].push(images_cargadas[name_image])}
success()})})}
establecerApariencia(){var avatar=this;var estado=avatar.estadoActual;switch(estado){case 'parado':avatar.image.width=512;avatar.image.height=1024;avatar.coords.px=50;avatar.coords.py=-750;break}
avatar.image.images=[];return new Promise(function(success,fail){var imagesDeEstado=avatar.imagesEstados[estado];if(!imagesDeEstado.image){var nImagesCrear=0,nImagesCreadas=0;var evaluarFinalizacion=function(){if(nImagesCrear<=nImagesCreadas){avatar.image.images=[imagesDeEstado.cuerpo.image,imagesDeEstado.cabeza.image];success()}}
for(var i in imagesDeEstado){let name_estado=i;nImagesCrear++;let canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=imagesDeEstado[i][0].width;canvas.height=imagesDeEstado[i][0].height;let images=imagesDeEstado[i];for(var img in images){ctx.drawImage(images[img],0,0)}
canvas.toBlob(function(blob){var image=new Image();image.src=URL.createObjectURL(blob);image.onload=function(){imagesDeEstado[name_estado].image=this;nImagesCreadas++;evaluarFinalizacion()}})}}else{avatar.image.images=[imagesDeEstado.cuerpo.image,imagesDeEstado.cabeza.image]}})}
mirada={desde:[],hacia:[]}
mirarHacia(coords_desde,coords_hacia){var ftgrama_y=0;if(this.mirada.desde.toString()==coords_desde.toString()&&this.mirada.hacia.toString()==coords_hacia.toString())
return;if(coords_desde[0]==coords_hacia[0]&&coords_desde[0]<coords_hacia[0]){ftgrama_y=0}else if(coords_desde[0]>coords_hacia[0]&&coords_desde[1]<coords_hacia[1]){ftgrama_y=1}else if(coords_desde[0]>coords_hacia[0]&&coords_desde[1]==coords_hacia[1]){ftgrama_y=2}else if(coords_desde[0]>coords_hacia[0]&&coords_desde[1]>coords_hacia[1]){ftgrama_y=3}else if(coords_desde[0]==coords_hacia[0]&&coords_desde[1]>coords_hacia[1]){ftgrama_y=4}else if(coords_desde[0]<coords_hacia[0]&&coords_desde[1]>coords_hacia[1]){ftgrama_y=5}else if(coords_desde[0]<coords_hacia[0]&&coords_desde[1]==coords_hacia[1]){ftgrama_y=6}else if(coords_desde[0]<coords_hacia[0]&&coords_desde[1]<coords_hacia[1]){ftgrama_y=7}
this.image.fotogramaY[0]=ftgrama_y;this.mirada.desde=coords_desde;this.mirada.hacia=coords_hacia}
visualizar(){super.visualizar(...arguments)}
caminar(casillas_recorrer){var time=ClientGame.Game.verTiempo();this.cancelarCaminata();this.caminata.casillas_recorrer=casillas_recorrer;this.caminata.time_inicio=time;this.caminata.time_inicio_casilla=time;this.caminata.enCurso=!0;this.crearAnimacion(0,"caminar","perpetua",[1,2,3,4],100);Avatar.AvataresCaminando.push(this)}
cancelarCaminata(){if(!this.caminata.enCurso)return!1;this.caminata.enCurso=!1;this.caminata.casillas_recorrer=[];this.caminata.time_inicio=0;this.caminata.time_inicio_casilla=0;this.caminata.caminos_recorridos=0;this.cancelarAnimacion(0);var indx=Avatar.AvataresCaminando.indexOf(this);if(indx!=-1){Avatar.AvataresCaminando.splice(indx,1)}}
calcularCaminata(time){var prox_coord=this.caminata.casillas_recorrer[this.caminata.caminos_recorridos];if(!prox_coord)return this.cancelarCaminata();var prox_casilla=ClientGame.Sala.verCasilla(prox_coord[0],prox_coord[1]),miCasilla=this.MiCasilla;if(time-this.caminata.time_inicio_casilla>=this.caminata.time_por_casilla){this.coords.cx=prox_coord[0];this.coords.cy=prox_coord[1];this.coords.caminata_x=0;this.coords.caminata_y=0;this.caminata.time_inicio_casilla=time;this.caminata.caminos_recorridos++;this.ubicarCuerpo()}else{let progreso=(time-this.caminata.time_inicio_casilla)/this.caminata.time_por_casilla;this.coords.caminata_x=(prox_casilla.posicion.px-miCasilla.posicion.px)*progreso;this.coords.caminata_y=(prox_casilla.posicion.py-miCasilla.posicion.py)*progreso;this.mirarHacia([this.coords.cx,this.coords.cy],prox_coord.slice())}}}
